### ISSUE TITLE
Availability in the Arch community repo and in the AUR is not a good idea

### ISSUE THREAD

**Issue by ghost** [orhun/gpg-tui#13]
I think the availability in the community repo and in the AUR is not a good idea because it can cause problems.

Better place the PKGBUILD in the project repo and remove (or rename) the AUR package.

Just my 2 cents.

**Comment by orhun** [comment]
Yes, I will remove the [gpg-tui](https://aur.archlinux.org/packages/gpg-tui) AUR package soon.
