### ISSUE TITLE
Add logging option

### ISSUE THREAD

**Issue by Narrat** [orhun/gpg-tui#136]
**Is your feature request related to a problem? Please describe.**

There may be the case, that the `gpg` setup or keyring causes problems within `gpg-tui`. Without any visible output such an issue can be difficult to pinpoint.
See for example https://github.com/orhun/gpg-tui/discussions/135

**Describe the solution you'd like**

An option or cli argument which enables some sort of logging. With this enabled `gpg-tui` provides information what it is doing behing the scenes and may help to pinpoint issues.

Possible implementation can look like [this](https://github.com/orhun/systeroid/#verbose-logging)

**Describe alternatives you've considered**

There is no real alternative? STDERR output directly into the terminal isn't viable with a ncurses TUI.

**Comment by orhun** [comment]
Implemented in #201 - now you can press `CTRL-L` / `F2` to see the application logs. Let me know if we need more verbosity!

![image](https://github.com/orhun/gpg-tui/assets/24392180/47bff76d-58d6-41d2-913c-7b1d9d900511)
