### ISSUE TITLE
NIST, Brainpool, & secp algorithms display as unrecognized

### ISSUE THREAD

**Issue by Le-Kat** [orhun/gpg-tui#154]
**Describe the bug**

Keys that use any NIST, Brainpool, or secp as their algorithm display as "unrecog".

**To Reproduce**

1. Run command `gpg --full-gen-key --expert`
2. Press key '9'
3. Select any NIST, Brainpool, or secp algorithm
4. Follow key generation instructions untill gpg key is generated
5. Open gpg-tui, see that the newly generated key has the algorithm set to "unrecog"

**Expected behavior**

gpg-tui should be displaying these key's algorithm, since they're supported by gpg (and gpg-tui does support curve25519)

**Screenshots/Logs**

![image](https://github.com/orhun/gpg-tui/assets/37410281/8b712f33-3c75-4599-84c9-452ec679c78e)

**System Information**

 - OS: `Arch Linux x86_64 6.5.9-arch2-1`
    
 - Rust Version: rustc 1.71.1 (eb26296b5 2023-08-03)
    
 - GPGME version: I'm unable to install gpgme-config to check (idk why)
    
 - GPGME engine version: `2.2.41`
    
 - Project Version: `0.10.0`

**Comment by orhun** [comment]
Hello, thanks for reporting this!

I pushed 2618d7515de2282818db326f5c202ec2649f42b9 which enables showing the algoritm name.

Feel free to build it from source and check if it works for you 🐻

**Comment by Le-Kat** [comment]
Yep, It displays the name now, thanks!
