### ISSUE TITLE
(neo)mutt integration?

### ISSUE THREAD

**Issue by roland-rollo** [orhun/gpg-tui#19]
Are there any plans for some integration or support for the (neo)mutt?

**Comment by orhun** [comment]
Currently no. It's because I don't really use mutt thus I cannot see how gpg-tui can be used to make things easier. I'd like to listen "how" though. Do you mean like a side-utility to manage PGP keys to encrypt/sign mails, by saying "integration/support"?

**Comment by syntezoid** [comment]
Yes, that's what I meant. Forgive me for an unspecified request.

**Comment by ki9us** [comment]
Haven't tested this, but if you want a key selector for the encryption recipients, you might be able to drop this in your muttrc: 

```
set pgp_encrypt_only_command="pgpewrap gpg --batch --quiet --no-verbose --output - --encrypt --textmode --armor --always-trust -- -r $(gpg-tui --select key_id) -- %f"
set pgp_encrypt_sign_command="pgpewrap gpg %?p?--passphrase-fd 0? --batch --quiet --no-verbose --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust -- -r $(gpg-tui --select key_id) -- %f"
```

**Comment by orhun** [comment]
Great trick @ki9us, thanks for sharing!
