### ISSUE TITLE
arch linux install: signature from "Orhun Parmaksız <orhun@archlinux.org>" is unknown trust

### ISSUE THREAD

**Issue by bdunbar** [orhun/gpg-tui#21]
**Describe the bug**

On installation using pacman error is recieved:
`signature from "Orhun Parmaksız <orhun@archlinux.org>" is unknown trust`

**To Reproduce**

1. `$ sudo pacman -S gpg-tui`

**Expected behavior**

Clean Install

**Screenshots/Logs**

[bdunbar@hilda ~]$ sudo pacman -S gpg-tui
resolving dependencies...
looking for conflicting packages...

Packages (1) gpg-tui-0.4.0-1

Total Installed Size:  1.59 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 gpg-tui-0.4.0-1-x86_64 is up to date
(1/1) checking keys in keyring                                                      [################################################] 100%
(1/1) checking package integrity                                                    [################################################] 100%
error: gpg-tui: signature from "Orhun Parmaksız <orhun@archlinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/gpg-tui-0.4.0-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] Y
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
[bdunbar@hilda ~]$ sudo pacman -S gpg-tui
resolving dependencies...
looking for conflicting packages...

Packages (1) gpg-tui-0.4.0-1

Total Download Size:   0.62 MiB
Total Installed Size:  1.59 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 gpg-tui-0.4.0-1-x86_64                                 637.8 KiB  1063 KiB/s 00:01 [################################################] 100%
(1/1) checking keys in keyring                                                      [################################################] 100%
(1/1) checking package integrity                                                    [################################################] 100%
error: gpg-tui: signature from "Orhun Parmaksız <orhun@archlinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/gpg-tui-0.4.0-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
[bdunbar@hilda ~]$

**System Information**

 - OS: [Linux 5.12.7-arch1-1 Arch LInux]

**Comment by orhun** [comment]
I checked the signature and the package and they both seem fine. I think you're having a keyring issue on your side. Can you try updating the keyring? (e.g. `pacman-key --refresh-keys`)

**Comment by bdunbar** [comment]
Issue persists.

1. Ran `pacman-key --refresh-keys`
2. `sudo pacman -S gpg-tui` returns same error as before for package  ` gpg-tui-0.4.1-1`

However I am able to install the AUR version correctly.

` yay -S gpg-tui-git`
`Packages (1) gpg-tui-git-0.4.1.r1.g80caab8-1`

This meets my need - and I sure appreciate the hard work you've put in.
