### ISSUE TITLE
gpg-tui does not recognise '~" as alias for the user's home directory

### ISSUE THREAD

**Issue by wararjey** [orhun/gpg-tui#22]
Hello Orhun,

you were so kind to the feature of exporting the secret subkeys, thank you.

Trying this feature, I discovered what I deem to be a bug:
When I set a specfific homedir or outdir using something like
`gpg-tui --outdir=~/anydir`
I would expect gpg-tui to write the exported keys to
`/home/myusername/anydir`
however, it actually writes the files to
`/home/myusername/~/anydir`

It seems the commonly used alias '~' for /home/myusername is not "translated" as other programs do.

Regards,

**Comment by orhun** [comment]
Good catch! I'll push a minor release fixing this issue soon. Thanks for reporting this!
