### ISSUE TITLE
when editing a key, one cpu core is 100% with gpg-tui

### ISSUE THREAD

**Issue by hasezoey** [orhun/gpg-tui#29]
**Describe the bug**

When using `gpg-tui` and editing a key (keybind `e`), then `gpg-tui` uses one core 100% at least until editing is done

**To Reproduce**

1.  i ran it with `./gpg-tui -a --style colored`
2. select an key (in my case it is this one, directly after import `curl https://github.com/web-flow.gpg | gpg --import`)
3. press `e` to edit the key
3.5. i dont know if it matters, but i saw the usage only after already having also entered`trust` (as seen in the screenshot)
4. look at htop (in my case its `btm`) or whatever and see that `gpg-tui` uses one core to 100%
4.5 after entering an trust level and saving (exiting gpg), gpg-tui cpu usage goes back to normal

**Expected behavior**

that gpg-tui does not use one core to 100%

**Screenshots/Logs**

btm:  
![Screenshot from 2021-07-20 12-37-41](https://user-images.githubusercontent.com/10911626/126310276-9cffacb1-e966-424b-a160-ee29db7b0cf6.png)

gpg-tui:  
![Screenshot from 2021-07-20 12-43-05](https://user-images.githubusercontent.com/10911626/126310981-6e478e85-174d-4c01-9a7f-d67a2ede7e29.png)

**System Information**

 - OS: `Linux Mint 20.2`
    
 - Rust Version: `rustc 1.53.0 (53cb7b09b 2021-06-17)`
    
 - GPGME version: `1.13.1-unknown`
    
 - GPG version: `gpg (GnuPG) 2.2.19` `libgcrypt 1.8.5`
    
 - Project Version: `gpg-tui 0.7.1` (git head `e0df8602b83e1bb1f02dcbaeb101b09b43f5713d`)
 - CPU: `Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz`

**Additional context**

Project was self compiled with `e0df8602b83e1bb1f02dcbaeb101b09b43f5713d` as git head and compiled with `cargo build --release` (nothing else modified)

**Comment by orhun** [comment]
I was able to reproduce this issue and it should be fixed with 53036ed. Thanks for reporting!
