### ISSUE TITLE
Problem building on Debian Testing

### ISSUE THREAD

**Issue by saemideluxe** [orhun/gpg-tui#42]
**Describe the bug**

Build fails on Debian Testing/Bookworm

**To Reproduce**

1. ```git clone https://github.com/orhun/gpg-tui.git && cd gpg-tui```
2. ```cargo build```
5. Build finishes with error ```error: argument for `--edition` must be one of: 2015|2018. (instead was `2021`)```

**Expected behavior**

Successfull build

**System Information**

 - OS: Debian Bookworm
 - Rust Version: rustc 1.50.0
 - GPGME version: 1.16.0-unknown
 - GPGME engine version: 2.2.27
 - Project Version: master

**Additional context**

I saw that the Rust edition of Debian Testing is *not* the edition inside ```Cargo.toml```. However, when I change the edition inside ```Cargo.toml``` I get a compilation error:

```bash
   Compiling gpg-tui v0.8.1 (/home/sam/git/gpg-tui)
error[E0277]: `[&str; 2]` is not an iterator
 --> src/app/util.rs:8:10
  |
8 |             .args(["/C", cmd])
  |                   ^^^^^^^^^^^
  |                   |
  |                   expected an implementor of trait `IntoIterator`
  |                   help: consider borrowing here: `&["/C", cmd]`
  |
  = note: the trait bound `[&str; 2]: IntoIterator` is not satisfied
  = note: required because of the requirements on the impl of `IntoIterator` for `[&str; 2]`

error[E0277]: `[&str; 2]` is not an iterator
  --> src/app/util.rs:13:10
   |
13 |             .args(["-c", cmd])
   |                   ^^^^^^^^^^^
   |                   |
   |                   expected an implementor of trait `IntoIterator`
   |                   help: consider borrowing here: `&["-c", cmd]`
   |
   = note: the trait bound `[&str; 2]: IntoIterator` is not satisfied
   = note: required because of the requirements on the impl of `IntoIterator` for `[&str; 2]`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `gpg-tui` due to 2 previous errors
```

It would an advantage for the project it if would be buildable on a recent Debian Testing environment. I guess I could download the most recent rust compiler and try to build it again, but maybe there is an easier way? In any case appreciate the work on this tool, it removes a lot of googling gpg flags from my life, thanks ;)

**Comment by orhun** [comment]
Hello!

I went back in time and tried to build `gpg-tui` with Rust 1.50.0 (2018 edition) to reproduce the issue. And it seems like fixing the compilation error does not affect anything at the current time! So here we go: 2ef4f755216ff587bf9b21beb7bf2cee4396f098

I hope that helps. Let me know if there is anything else that I can do 🐻

**Comment by saemideluxe** [comment]
Many thanks!

Builds now without problems.

For other Debian users encountering this issue: Building this will
require to change the line ```edition = "2021"``` inside
```Cargo.toml``` to be ```edition = "2021"```.  Also the packages
libxcb-shape0-dev and libxcb-xfixes0-dev are required for building.
