### ISSUE TITLE
Add a configuration file

### ISSUE THREAD

**Issue by orhun** [orhun/gpg-tui#5]
**Is your feature request related to a problem? Please describe.**

Having a configuration file for managing the application settings would be good in the future. (It looks like it's going to be needed anyways.)

**Describe the solution you'd like**

Implement a configuration file parser using `config` or `rust-ini` crates. Update the config values in the application after parsing this file.

**Comment by devhell** [comment]
This would be great, especially also to define colorschemes using, for example, [flavours](https://github.com/Misterio77/flavours/). 

Also, I'd just like to say thank you for creating this really cool TUI. I've been looking for something like this for ages. :smile:

**Comment by orhun** [comment]
It should be also possible to change the file explorer utility (default: `xplr`) with using the config file.

**Comment by orhun** [comment]
The configuration file is implemented now. (See [#configuration](https://github.com/orhun/gpg-tui#configuration))

I dispersed the other mentioned issues to their separate issues: #31 #32

Closing.

**Comment by devhell** [comment]
Amazing, thank you!
