### ISSUE TITLE
Error: missing field `detail_level` for key `general` at line 25 column 1

### ISSUE THREAD

**Issue by Mellbourn** [orhun/gpg-tui#53]
**Describe the bug**

When I start gpg-tui I immediately get this message and it then exits
```
Error: missing field `detail_level` for key `general` at line 25 column 1
```

**To Reproduce**

1. Run gpg-tui
2. See error

**Expected behavior**

No error, GUI instead.

**System Information**

 - OS: macOS Ventura 13.2
    
 - Rust Version: 1.67.0
    
 - GPGME version: 1.18.0
    
 - GPGME engine version: 2.4.0
    
 - Project Version: 0.9.3

**Comment by orhun** [comment]
Hello, thanks for reporting this! 🐻

It's a regression in 849d90df3a51a33c0fb2b863988282d8f645c5b3 and should be fixed via 0cecc714be9d0a37c7885aebdf5d1c6c055ccf97.

I will be releasing a new version shortly.

**Comment by orhun** [comment]
[v0.9.4](https://github.com/orhun/gpg-tui/releases/tag/v0.9.4) is out!

**Comment by Mellbourn** [comment]
I've confirmed that 0.9.4 works for me.
Thank you!
