### ISSUE TITLE
Notation support

### ISSUE THREAD

**Issue by YarmoM** [orhun/gpg-tui#8]
**Is your feature request related to a problem? Please describe.**

Notations are a way to add simple custom data to a key/signature. [Keyoxide](https://keyoxide.org) makes extensive use of them to add identity claims to OpenPGP keys ([example](https://keyoxide.org/guides/github)). Currently, gpg-tui does not display notations or allow notaton management through its interface.

**Describe the solution you'd like**

It would be great if gpg-tui could display the notations stored inside keys and provide shortcuts to add/delete notations.

**Describe alternatives you've considered**

Not applicable.

**Additional context**

As maintainer of Keyoxide, I am always looking for ways/tools to make cryptographic key management easier. I will start recommending this project to people inexperienced with GPG. If this project were to support notations, that would make this great tool even greater for usage with Keyoxide.

**Comment by YarmoM** [comment]
As an unrelated comment, the project looks great! Glad to see new tools being developed for gpg

**Comment by orhun** [comment]
> It would be great if gpg-tui could display the notations stored inside keys

Best and easiest way of displaying notations would be showing them on detail level 3 (signatures) I think. So while showing the signatures, I can also list the notations associated with the signature. Something like this:

![gpg-tui-notations](https://user-images.githubusercontent.com/24392180/120848120-0fb47280-c57d-11eb-9003-1e19be6e85eb.gif)

Notation format is the following:

```
[h] test@notation3=testxyz
 │   │               └─ notation value
 │   └─ notation name
 └─ notation flag ("h": human readable, "!": critical)
```

I already implemented it, what do you think?

> and provide shortcuts to add/delete notations.

AFAIK this is done by using `gpg --edit-key` and gpg-tui already provides a shortcut for running this command on the selected key. Implementing separate shortcuts for add/delete is pretty costly. Instead, solving this in #16 makes more sense for now.

> [Keyoxide](https://keyoxide.org) makes extensive use of them to add identity claims to OpenPGP keys ([example](https://keyoxide.org/guides/github)).

Wow, cool project. I'll check it out.

> As maintainer of Keyoxide, I am always looking for ways/tools to make cryptographic key management easier. I will start recommending this project to people inexperienced with GPG. If this project were to support notations, that would make this great tool even greater for usage with Keyoxide.

🥂

**Comment by YarmoM** [comment]
I think that is absolutely amazing, a great way to quickly inspect the notations of a key! I love it :heart: 

And indeed, #16 would be a great addition to your tool.

**Comment by orhun** [comment]
Cool! I'll ship a new release soon.
